import { CUISINES, FOOD_TYPES } from '@constants';

import { addRestaurantContent } from './addEditRestaurant.constants';

export const menuFields = [
    {
        name: 'name',
        type: 'text',
        label: addRestaurantContent.DISH_NAME_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'cuisine',
        type: 'select',
        label: addRestaurantContent.DISH_CUISINE_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
        options: CUISINES,
    },
    {
        name: 'food_type',
        type: 'select',
        label: addRestaurantContent.DISH_FOOD_TYPE_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
        options: FOOD_TYPES,
    },
    {
        name: 'price_amount',
        type: 'number',
        label: addRestaurantContent.DISH_PRICE_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'stock',
        type: 'number',
        label: addRestaurantContent.DISH_STOCK_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'image_link',
        type: 'image',
        label: addRestaurantContent.DISH_IMAGE_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'description',
        type: 'text',
        label: addRestaurantContent.DISH_DESCRIPTION_LABEL,
        grid: { xs: 12 },
        multiline: false,
        rows: undefined,
    },
];

export const restaurantBasicInfoFields = [
    {
        name: 'logo_link',
        type: 'image',
        label: addRestaurantContent.RESTAURANT_LOGO_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'image_link',
        type: 'image',
        label: addRestaurantContent.RESTAURANT_BANNER_IMAGE_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
    },
];

export const addressFields = [
    {
        name: 'address.street',
        type: 'text',
        label: addRestaurantContent.STREET_LABEL,
        grid: { xs: 12 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'address.city',
        type: 'text',
        label: addRestaurantContent.CITY_LABEL,
        grid: { xs: 12, md: 4 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'address.state',
        type: 'text',
        label: addRestaurantContent.STATE_LABEL,
        grid: { xs: 12, md: 4 },
        multiline: false,
        rows: undefined,
    },
    {
        name: 'address.pincode',
        type: 'text',
        label: addRestaurantContent.PIN_CODE_LABEL,
        grid: { xs: 12, md: 4 },
        multiline: false,
        rows: undefined,
    },
];

export const restaurantInfoFields = [
    {
        name: 'name',
        type: 'text',
        label: addRestaurantContent.RESTAURANT_NAME_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
        required: true,
        disabled:false,
    },
    {
        name: 'description',
        type: 'text',
        label: addRestaurantContent.RESTAURANT_DESCRIPTION_LABEL,
        grid: { xs: 12 },
        multiline: true,
        rows: 4,
        required: false,
    },
    {
        name: 'country_code',
        type: 'text',
        label: addRestaurantContent.COUNTRY_CODE,
        grid: { xs: 12, sm: 4, md:2 },
        multiline: false,
        rows: undefined,
        required: true,
        disabled:false,
    },
    {
        name: 'contact_number',
        type: 'text',
        label: addRestaurantContent.RESTAURANT_CONTACT_NUMBER_LABEL,
        grid: { xs: 12, sm: 8 ,md:4},
        multiline: false,
        rows: undefined,
        required: true,
        disabled:true,
    },
    {
        name: 'email',
        type: 'text',
        label: addRestaurantContent.RESTAURANT_EMAIL_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
        required: true,
        disabled:true,
    },
    {
        name: 'food_type',
        type: 'select',
        label: addRestaurantContent.DISH_FOOD_TYPE_LABEL,
        grid: { xs: 12, md: 6 },
        multiline: false,
        rows: undefined,
        options: FOOD_TYPES,
        required: true,
        disabled:false,
    },
];
