import { FieldPath } from 'react-hook-form';

import { AddRestaurantFormData } from './AddEditRestaurant.types';

export const addRestaurantContent = {
    RESTAURANT_HEADING: 'ADD NEW RESTAURANT',
    RESTAURANT_SUBHEADING:
        'Add your restaurant and start serving customers through our platform',
    BACK: 'Back',
    CANCEL: 'cancel',
    NEXT: 'Next',
    SUBMIT: 'Submit',
    ADD_RESTAURANT_DIALOG_TITLE: 'Cancel Adding New Restaurant.',
    EDIT_RESTAURANT_DIALOG_TITLE: 'Cancel Editing Restaurant.',
    ADD_RESTAURANT_DIALOG_SUBTITLE: 'Do you want to cancel  adding restaurant?',
    EDIT_RESTAURANT_DIALOG_SUBTITLE:
        'Do you want to cancel editing  new restaurant?',
    DIALOG_LABEL: 'Confirm',
    MENU_ITEMS_TITLE: 'Menu Item',
    ADD_MENU_BUTTON: 'Add Menu Item',
    MENU_DIALOG_TITLE: 'Delete Menu Item.',
    MENU_DIALOG_SUBTITLE: 'Do you want to delete menu item?',
    DISH_NAME_LABEL: 'Dish Name',
    DISH_CUISINE_LABEL: 'Cuisine *',
    DISH_FOOD_TYPE_LABEL: 'Food Type *',
    DISH_PRICE_LABEL: 'Dish Price',
    DISH_STOCK_LABEL: 'Stock',
    DISH_IMAGE_LABEL: 'Image url..',
    DISH_IMAGE_ALT: 'Dish Image',
    DISH_DESCRIPTION_LABEL: 'Description',
    RESTAURANT_INFO_HEADING: 'Basic Restaurant Information',
    RESTAURANT_LOGO_LABEL: 'Logo URL ',
    RESTAURANT_LOGO_ALT: 'Restaurant logo',
    RESTAURANT_BANNER_IMAGE_ALT: 'Restaurant banner image',
    RESTAURANT_BANNER_IMAGE_LABEL: 'Image URL',
    ADDRESS_HEADING: 'Address',
    STREET_LABEL: 'Street',
    STATE_LABEL: 'State',
    CITY_LABEL: 'City',
    PIN_CODE_LABEL: 'Pincode',
    TIMINGS_HEADING: 'Restaurant Hours',
    OPENING_TIME_LABEL: 'Opening Time *',
    CLOSING_TIME_LABEL: 'Closing Time *',
    WORKING_DAYS_LABEL: 'Working Days *',
    OWNER_NAME_LABEL: 'Owner Name (Read only)',
    RESTAURANT_NAME_LABEL: 'Restaurant Name',
    RESTAURANT_DESCRIPTION_LABEL: 'Description',
    RESTAURANT_CONTACT_NUMBER_LABEL: 'Contact Number',
    RESTAURANT_EMAIL_LABEL: 'Email',
    RESTAURANT_CUISINES_LABEL: 'Cuisines *',
    RESTAURANT_NAME_REQUIRED: 'Restaurant name is required',
    EMAIL_VALIDATION: 'Enter a valid email',
    EMAIL_REQUIRED: 'email is required',
    RESTAURANT_CONTACT_NUMBER_REQUIRED: 'Contact Number is required',
    RESTAURANT_CONTACT_NUMBER_VALIDATION: 'invalid phone',
    RESTAURANT_FOOD_TYPE_REQUIRED: 'Restaurant food type is required',
    STREET_REQUIRED: 'Street is required',
    CITY_REQUIRED: 'City is required',
    STATE_REQUIRED: 'State is required',
    PINCODE_REQUIRED: 'Pincode is required',
    PINCODE_VALIDATION: 'The field must contain only numbers',
    OPENING_TIME_REQUIRED: 'Opening time is required',
    CLOSING_TIME_REQUIRED: 'Closing time is required',
    CLOSING_TIME_VALIDATION: 'closing-validation',
    CLOSING_TIME_VALIDATION_ERROR:
        'Closing time must be later than opening time.',
    DAY_REQUIRED: 'Day is required',
    DAY_VALIDATION: 'Select at least one working day',
    ITEM_NAME_REQUIRED: 'Item name is required',
    ITEM_CUISINE_REQUIRED: 'cuisine is required',
    ITEM_FOOD_TYPE_REQUIRED: 'Food type is required',
    PRICE_REQUIRED: 'Price is required',
    POSITIVE_PRICE_VALIDATION: 'Price must be greater than 0',
    ITEM_STOCK_REQUIRED: 'Stock is required',
    ITEM_STOCK_VALIDATION: 'Stock cannot be less than 0',
    ATLEAST_ONE_ITEM_VALIDATION: 'Add at least one menu item',
    SNACKBAR_ERROR_MESSAGE: 'Error while fetching restaurant data.',
    RESTAURANT_CUISINES_VALIDATION: 'Select at least one cuisine',
    RESTAURANT_CUISINES_REQUIRED: 'Cuisines are required',
    RESTAURANT_EDIT: 'Edit Restaurant',
    COUNTRY_CODE:"Country Code",
    DELETE_ITEM_CONFIRM_LABEL: 'Yes Delete',
    ITEM_ADDED_MESSAGE: 'Item added successful.',
    ITEM_UPDATED_MESSAGE:"Item updated successfully",
    FETCH_MENU_ERROR: 'Error while fetching menu',
    COUNTRY_CODE_REQUIRED:'country code is required.'
};

export const STEP_FIELDS: FieldPath<AddRestaurantFormData>[][] = [
    ['name', 'email', 'description', 'contact_number', 'food_type', 'cuisines'],
    [
        'logo_link',
        'image_link',
        'opening_time',
        'closing_time',
        'is_available',
        'working_days',
        'address.street',
        'address.city',
        'address.state',
        'address.pincode',
    ],
    ['menu'],
];
