export const actionLabels = {
    LOGOUT: 'Logout',
    ACCOUNT_OPEN: 'account-menu',
    ACCOUNT_LABEL: 'open account menu',
    CANCEL: 'Cancel',
    SUBMIT: 'Submit',
    ADD: 'Add',
    CONFIRM: 'Confirm',
    SAVE: 'Save',
    EDIT: 'Edit',
    BACK: 'Back',
    DELETE: 'Delete',
    OUT_OF_STOCK: 'Out Of Stock',
    PROFILE: 'Profile',
};
