export const authContent = {
    LOGIN_HEADING: 'WELCOME BACK',
    LOGIN_SUBHEADING: 'Sign in to continue ordering you favourite food',
    EMAIL_FIELD: 'Email',
    PASSWORD_FIELD: 'Password',
    NAME_FIELD: 'Name',
    CONFIRM_PASSWORD_FIELD: 'Confirm Password',
    ROLE_FILED: 'Join as Restaurant Partner',
    LOGIN_BUTTON: 'Login',
    LOGIN_HELPER_TEXT: 'Don&apos;t have an account?',
    SIGNUP_BUTTON: 'Sign Up',
    SIGNUP_HELPER_TEXT: 'Already have an account?',
    SIGNUP_HEADING: 'START ORDERING',
    SIGNUP_SUBHEADING: 'Sign up to start ordering you favourite food',
    NAME_PLACEHOLDER: 'Enter your name',
    EMAIL_PLACEHOLDER: 'Enter your email',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Enter password again',
};
